"""
Skills taxonomy and generic phrases for resume analysis.
"""
SKILL_KEYWORDS = [
    "Python", "Java", "JavaScript", "TypeScript", "C++", "C#", "Go", "Rust",
    "SQL", "NoSQL", "MongoDB", "PostgreSQL", "MySQL", "Redis", "Cassandra",
    "TensorFlow", "PyTorch", "Keras", "scikit-learn", "NumPy", "Pandas",
    "Docker", "Kubernetes", "AWS", "Azure", "GCP", "Terraform", "Ansible",
    "Git", "Jenkins", "CI/CD", "Linux", "Bash", "Shell",
    "React", "Vue.js", "Angular", "Node.js", "Django", "Flask", "FastAPI",
    "Spring Boot", "REST APIs", "GraphQL", "gRPC",
    "Machine Learning", "Deep Learning", "NLP", "Computer Vision",
    "BERT", "LLM", "RAG", "LangChain", "Hugging Face",
    "Spark", "Hadoop", "Kafka", "Airflow", "ETL",
    "Agile", "Scrum", "JIRA", "Confluence",
    "Blockchain", "Solidity", "Web3",
    "Cybersecurity", "Network Security", "Penetration Testing",
    "Tableau", "Power BI", "Excel",
    "Project Management", "Leadership", "Team Management",
    "Communication", "Problem Solving", "Critical Thinking",
    "SEO", "Digital Marketing", "Content Strategy",
    "Accounting", "Financial Analysis", "Risk Management",
    "AutoCAD", "SolidWorks", "MATLAB",
    "FPGA", "Embedded C", "RTOS",
    "OOP", "Data Structures", "Algorithms", "System Design",
    "Microservices", "DevOps", "MLOps", "Data Engineering",
    "Cloud Computing", "Edge Computing", "IoT",
]

JOB_CATEGORIES = {
    "Engineering": ["Software Engineer", "Backend Developer", "Frontend Developer",
                    "Full-Stack Developer", "DevOps Engineer", "Cloud Engineer",
                    "Data Engineer", "MLOps Engineer", "Site Reliability Engineer"],
    "AI_ML": ["Machine Learning Engineer", "Data Scientist", "AI Engineer",
              "Research Scientist", "Computer Vision Engineer", "NLP Engineer"],
    "Management": ["Product Manager", "Project Manager", "Engineering Manager",
                   "Technical Lead", "Team Lead"],
    "Design": ["UI/UX Designer", "Product Designer", "Graphic Designer"],
    "Security": ["Cybersecurity Engineer", "Security Analyst", "Penetration Tester",
                 "Security Architect"],
    "Data": ["Data Analyst", "Data Engineer", "Data Scientist", "Business Analyst"],
    "IT": ["System Administrator", "Network Engineer", "IT Support", "Database Administrator"],
    "Finance": ["Financial Analyst", "Accountant", "Auditor", "Finance Manager"],
    "HR": ["Human Resources Manager", "HR Coordinator", "Recruiter"],
    "Marketing": ["Marketing Manager", "Digital Marketing Specialist", "SEO Specialist"],
}

GENERIC_PHRASES = [
    "results-driven", "team player", "think outside the box", "go-getter",
    "self-starter", "detail-oriented", "highly motivated", "passionate about",
    "hardworking", "dedicated professional", "proven track record",
    "excellent communication skills", "strong work ethic", "creative thinker",
    "problem solver", "people person", "quick learner", "strategic thinker",
    "customer-focused", "results oriented", "hit the ground running",
    "synergy", "leverage", "utilize", "dynamic", "innovative",
    "forward-thinking", "take initiative", "work well under pressure",
    "multitasker", "team-oriented", "goal-oriented", "action-oriented",
    "deep dive", "drill down", "breadth and depth", "best in class",
    "world-class", "cutting-edge", "state-of-the-art", "bleeding edge",
    "think strategically", "drive results", "make an impact",
    "deliver value", "add value", "business acumen",
    "stakeholder management", "cross-functional", "end-to-end",
    "holistic approach", "out of the box", "blue sky thinking",
    "win-win", "low hanging fruit", "move the needle",
    "paradigm shift", "streamline", "optimize", "synergize",
    "circle back", "touch base", "align", "bandwidth", "deep dive",
    "key player", "game changer", "thought leader",
    "best of breed", "enterprise-grade", "scalable",
    "sought after", "in high demand", "ninja", "guru", "rockstar",
]
